FROM node:lts-alpine

# RUN npm install -g http-server

WORKDIR /src/app/frontend

COPY package*.json ./

RUN npm install

COPY . .

# RUN npm run build

EXPOSE 8080

# CMD ["npm", "run", "serve"]
# CMD [ "http-server", "dist" ]
CMD ["yarn", "serve"]

